require 'app/scenes/title_scene.rb'
require 'app/scenes/game_scene.rb'
require 'app/entities/base.rb'
require 'app/entities/static_entity.rb'
require 'app/entities/mobile_entity.rb'
require 'app/entities/floor.rb'
require 'app/entities/wall.rb'
require 'app/controllers/map_controller.rb'